using System.Collections.Generic;
using Fusion;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// Editor-only helper for checking whether card UI fits the hand/card panel without entering Play Mode.
///
/// Setup:
/// 1) Add this component to the same GameObject as InventoryUI, or any UI GameObject in the scene.
/// 2) Drag the same cardPrefab and handContainer used by InventoryUI.
/// 3) Drag CardData assets into mockCards, or press "Load All CardData Assets" in the Inspector.
/// 4) Press "Mock Cards Now" while NOT in Play Mode.
///
/// This intentionally uses CardUI.SetupNetworked(...), so the preview is as close as possible
/// to the runtime card spawning path used by InventoryUI.InitializeHand().
/// </summary>
[ExecuteAlways]
public class CardPanelMockTester : MonoBehaviour
{
    [System.Serializable]
    public class MockCardSlot
    {
        public CardData data;

        [Tooltip("-1 = use CardData.maxUses. 0 = show used-out state with X overlay.")]
        public int remainingUses = -1;

        [Min(0)] public int currentCooldown = 0;
    }

    [Header("References - same as InventoryUI")]
    public GameObject cardPrefab;
    public Transform handContainer;

    [Header("Mock Cards")]
    public List<MockCardSlot> mockCards = new List<MockCardSlot>();

    [Header("Options")]
    [Tooltip("Runtime InventoryUI clears the hand container before spawning cards. Keep this ON to preview the same layout behavior.")]
    public bool clearExistingChildren = true;

    [Tooltip("If true, only objects generated by this tester are cleared. If false and clearExistingChildren is true, all children are cleared like runtime InventoryUI.")]
    public bool clearOnlyGeneratedMockCards = false;

    [Tooltip("Disable card buttons in editor preview so accidental clicks do not invoke runtime card logic.")]
    public bool disableButtonsInMock = true;

    private const string MockPrefix = "__MOCK_CARD_UI__";

    private void Reset()
    {
        TryAutoBindFromInventoryUI();
    }

    private void OnValidate()
    {
        if (cardPrefab == null || handContainer == null)
            TryAutoBindFromInventoryUI();
    }

    [ContextMenu("Mock Cards Now")]
    public void MockCardsNow()
    {
        TryAutoBindFromInventoryUI();

        if (cardPrefab == null)
        {
            Debug.LogError("[CardPanelMockTester] Missing cardPrefab. Drag the same prefab used by InventoryUI.cardPrefab.", this);
            return;
        }

        if (handContainer == null)
        {
            Debug.LogError("[CardPanelMockTester] Missing handContainer. Drag the same Transform used by InventoryUI.handContainer.", this);
            return;
        }

        if (clearExistingChildren)
            ClearCardsInternal(clearOnlyGeneratedMockCards);

        int spawned = 0;

        for (int i = 0; i < mockCards.Count; i++)
        {
            MockCardSlot slot = mockCards[i];
            if (slot == null || slot.data == null)
                continue;

            GameObject go = InstantiateCardPrefab();
            if (go == null)
                continue;

            go.name = $"{MockPrefix}_{i:00}_{slot.data.cardName}";

            CardUI cardUI = go.GetComponent<CardUI>();
            if (cardUI == null)
            {
                Debug.LogError($"[CardPanelMockTester] Card prefab '{cardPrefab.name}' does not have CardUI on its root object.", cardPrefab);
                SafeDestroy(go);
                continue;
            }

            NetworkCardInstance netCard = new NetworkCardInstance
            {
                cardDataIndex = i,
                currentCooldown = Mathf.Max(0, slot.currentCooldown),
                remainingUses = ResolveRemainingUses(slot),
                isInitialized = true
            };

            // Use the real runtime setup method so size, artwork, text, cooldown overlay,
            // button state, and prefab layout are previewed like the actual game.
            cardUI.SetupNetworked(netCard, slot.data, i, _ => { });

            if (disableButtonsInMock && cardUI.cardButton != null)
                cardUI.cardButton.interactable = false;

            spawned++;
        }

#if UNITY_EDITOR
        if (!Application.isPlaying)
        {
            EditorUtility.SetDirty(this);
            EditorUtility.SetDirty(handContainer);
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(gameObject.scene);
        }
#endif

        Debug.Log($"[CardPanelMockTester] Mock spawned {spawned} card(s) into '{handContainer.name}'.", this);
    }

    [ContextMenu("Clear Mock Cards")]
    public void ClearMockCards()
    {
        ClearCardsInternal(true);
        Debug.Log("[CardPanelMockTester] Cleared generated mock card(s).", this);
    }

    [ContextMenu("Clear All Children In Hand Container")]
    public void ClearAllChildrenInHandContainer()
    {
        ClearCardsInternal(false);
        Debug.Log("[CardPanelMockTester] Cleared all child object(s) in hand container.", this);
    }

    [ContextMenu("Bind From InventoryUI")]
    public void TryAutoBindFromInventoryUI()
    {
        InventoryUI inventory = GetComponent<InventoryUI>();
        if (inventory == null)
            inventory = GetComponentInParent<InventoryUI>();
        if (inventory == null)
            inventory = GetComponentInChildren<InventoryUI>(true);

        if (inventory == null)
            return;

        if (cardPrefab == null)
            cardPrefab = inventory.cardPrefab;

        if (handContainer == null)
            handContainer = inventory.handContainer;
    }

    private int ResolveRemainingUses(MockCardSlot slot)
    {
        if (slot.remainingUses >= 0)
            return slot.remainingUses;

        if (slot.data != null)
            return Mathf.Max(0, slot.data.maxUses);

        return 1;
    }

    private GameObject InstantiateCardPrefab()
    {
#if UNITY_EDITOR
        if (!Application.isPlaying)
        {
            GameObject prefabInstance = PrefabUtility.InstantiatePrefab(cardPrefab, handContainer) as GameObject;
            if (prefabInstance != null)
            {
                RectTransform rect = prefabInstance.transform as RectTransform;
                if (rect != null)
                {
                    rect.localScale = Vector3.one;
                    rect.localRotation = Quaternion.identity;
                }
                else
                {
                    prefabInstance.transform.localScale = Vector3.one;
                    prefabInstance.transform.localRotation = Quaternion.identity;
                }
            }
            return prefabInstance;
        }
#endif

        return Instantiate(cardPrefab, handContainer);
    }

    private void ClearCardsInternal(bool generatedOnly)
    {
        if (handContainer == null)
            return;

        for (int i = handContainer.childCount - 1; i >= 0; i--)
        {
            Transform child = handContainer.GetChild(i);
            if (generatedOnly && !child.name.StartsWith(MockPrefix))
                continue;

            SafeDestroy(child.gameObject);
        }

#if UNITY_EDITOR
        if (!Application.isPlaying)
        {
            EditorUtility.SetDirty(handContainer);
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(gameObject.scene);
        }
#endif
    }

    private void SafeDestroy(GameObject target)
    {
        if (target == null)
            return;

#if UNITY_EDITOR
        if (!Application.isPlaying)
            DestroyImmediate(target);
        else
            Destroy(target);
#else
        Destroy(target);
#endif
    }

#if UNITY_EDITOR
    public void LoadAllCardDataAssets()
    {
        mockCards.Clear();

        string[] guids = AssetDatabase.FindAssets("t:CardData");
        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            CardData data = AssetDatabase.LoadAssetAtPath<CardData>(path);
            if (data == null)
                continue;

            mockCards.Add(new MockCardSlot
            {
                data = data,
                remainingUses = -1,
                currentCooldown = 0
            });
        }

        EditorUtility.SetDirty(this);
        Debug.Log($"[CardPanelMockTester] Loaded {mockCards.Count} CardData asset(s).", this);
    }
#endif
}

#if UNITY_EDITOR
[CustomEditor(typeof(CardPanelMockTester))]
public class CardPanelMockTesterEditor : Editor
{
    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        CardPanelMockTester tester = (CardPanelMockTester)target;

        EditorGUILayout.Space(10);
        EditorGUILayout.LabelField("Editor Mock Actions", EditorStyles.boldLabel);

        using (new EditorGUILayout.HorizontalScope())
        {
            if (GUILayout.Button("Bind From InventoryUI"))
                tester.TryAutoBindFromInventoryUI();

            if (GUILayout.Button("Load All CardData Assets"))
                tester.LoadAllCardDataAssets();
        }

        using (new EditorGUILayout.HorizontalScope())
        {
            if (GUILayout.Button("Mock Cards Now"))
                tester.MockCardsNow();

            if (GUILayout.Button("Clear Mock Cards"))
                tester.ClearMockCards();
        }

        if (GUILayout.Button("Clear All Children In Hand Container"))
            tester.ClearAllChildrenInHandContainer();

        EditorGUILayout.HelpBox(
            "Dùng để preview card UI trong Edit Mode, không cần Play/Build. Script này gọi CardUI.SetupNetworked giống InventoryUI khi game chạy, nên artwork/text/uses/cooldown/button state sẽ giống runtime nhất có thể.",
            MessageType.Info);
    }
}
#endif
